MCU        = RP2040
BOOTLOADER = rp2040

SPLIT_TRANSPORT = serial
SERIAL_DRIVER   = vendor

VIA_ENABLE      = no
LTO_ENABLE      = yes
CONSOLE_ENABLE  = no
COMMAND_ENABLE  = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

