#pragma once

#define MASTER_LEFT

#define SERIAL_DEBUG
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 1000

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP6
#define SERIAL_USART_RX_PIN GP7
#define WS2812_DI_PIN_RIGHT GP28

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP16

#ifndef CHORDAL_HOLD
#define CHORDAL_HOLD
#endif

